name: base
channels:
  - defaults
dependencies:
  - mamba
  - snakemake
  - ca-certificates
  - certifi
  - openssl
  - star=2.6.1
  - minimap2=2.22
  - pysam
  - pybedtools
  - biopython
  - bcbiogff
  - r-base
  - r-essentials
  - gffread
  - java-jdk
  - pbsv=2.6.2
  - pbmm2=1.4.0
  - pbbam=1.6.0
  - bam2fastx=1.3
  - samtools
  - bbmap
  - salmon=0.14.1
  - tbb=2020.2
  - scikit-learn=0.23.2 
